spring:
  profiles:
  application:
    name: test
	
server:
  port: 8021	
	
spring:
  profiles: dev
  application:
    name: dev

	
spring:
  profiles: test
  application:
    name: test
